### ISSUE TITLE
Minor changes need to take care

### ISSUE THREAD

**Issue by ankitkanojia** [gothinkster/react-redux-realworld-example-app#147]
Functionality work perfectly!!! ... Perfect work but found minor bug so that you should take care.
1) After post comment textarea not cleared.
2) On click of edit post TAGS value not render and auto filled up.

**Comment by oussamabouchareb** [comment]
it shouldn't be a big problem, as this app is supposed to be an example not a polished product

**Comment by ankitkanojia** [comment]
Okay, I think its a very good example of redux, still it's not polished then no worries.
