### ISSUE TITLE
browser history inconsistent

### ISSUE THREAD

**Issue by mvayngrib** [gothinkster/react-redux-realworld-example-app#29]
awesome project!

now the complaint :) 
I have no way of telling which clicks create browser history and which don't. 
Clicking tags doesn't. 
Clicking Home / Settings / New Post does. 
Clicking Your Feed / Global Feed doesn't. 

As a result, when I hit the back button, I have no idea where i'm going back to

**Comment by vkarpov15** [comment]
Yeah the ones that don't are meant to be part of the same view, like your feed / global feed. Maybe not perfect ux but was meant as a lesson on building tabs without react router. Thanks for your comments :+1:
