### ISSUE TITLE
Using pre-build middlewares like redux-saga or redux-thunk

### ISSUE THREAD

**Issue by hhsadiq** [gothinkster/react-redux-realworld-example-app#33]
Hey guys, first of all huge thanks for putting down this great demo. I am using this example to bootstrap my real world project. 

Just want to know the reason behind design decision to not use popular redux middlewares like redux-saga or redux-thunk and writing own middleware. I know its working well, but just curious. And is there possibility that using such pre-build, well-tested middlewares may reduce our code and improve its quality..?

And sorry I am missing something trivial, I am still new to React/Redux world so learning along.

**Comment by vkarpov15** [comment]
Remember that the purpose of this projects is educational - it's for learning react and redux. You need to learn how to write middleware to have a solid understanding of redux fundamentals, so this course instructs you how to write your own with several examples. Using a pre built plugin might make for a better starter, but it also skips an opportunity to learn something.

**Comment by hhsadiq** [comment]
Good point. Thanks
