### ISSUE TITLE
CSS styles?

### ISSUE THREAD

**Issue by ramsgoli** [gothinkster/react-redux-realworld-example-app#39]
More of a question rather than an issue, but following along with this file structure, where should the css styles be placed? Thanks!

**Comment by EricSimons** [comment]
Great question — if you had additional styles you wanted to add, you can either use inline styles or import a css stylesheet. This repo uses the create-react-app as the base, so you can import CSS in any component file by just importing a relative-path CSS file (`import './componentStyles.css';`)

If you choose to do inline styles, I highly recommend [Glamorous](https://github.com/paypal/glamorous) from @kentcdodds. I've been using it lately and it's absolutely fantastic.

**Comment by kentcdodds** [comment]
That's awesome to hear! Would you like to add yourself to the [`USERS.md`](https://github.com/paypal/glamorous/blob/master/other/USERS.md)!?

**Comment by EricSimons** [comment]
Definitely! Just submitted a PR :)
