### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by SandeeshS** [gothinkster/react-redux-realworld-example-app#48]
The pagination on user articles, favorites and feed are broken. Clicking on any of the paginated pages at the bottom will trigger a call to the all articles api endpoint and reset the data and pagination to the global feed. Might be because of this.

https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/src/components/ListPagination.js#L20

Tested on here https://react-redux.realworld.io

**Comment by EricSimons** [comment]
Good catch — will dig into this over the wknd/early next wk. If someone wants to take a stab at it, we'll accept any PR's!

**Comment by SandeeshS** [comment]
This was fixed with https://github.com/gothinkster/react-redux-realworld-example-app/pull/49. But the demo still has the bug. Is the code manually deployed?

**Comment by EricSimons** [comment]
Indeed — I'll need to pull & redeploy. Might be good to get this set up on github pages so we can have them always be in sync 🤔

**Comment by SandeeshS** [comment]
@EricSimons you could also add a webhook to pull the code to prod on updates to the master branch. But you need to be sure before going through with merges since there are no tests in place atm to find fault in PRs.

**Comment by SandeeshS** [comment]
Was fixed with #49
