### ISSUE TITLE
Default port is conflicting with node/rails backend

### ISSUE THREAD

**Issue by deksden** [gothinkster/react-redux-realworld-example-app#52]
Default port for React app is conflicting with Node's default port 3000. It will be better to change it, because for Rails app 3000 is also default port.

Just look at angular projects with 4000+ port range.

**Comment by deksden** [comment]
We can add .env file for port (https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-development-environment-variables-in-env)

or we can change package.json's start script (not sure if its cross platform):  some discussion is here: https://github.com/facebookincubator/create-react-app/issues/1083

IMHO, .env way is better.

**Comment by SandeeshS** [comment]
Most of the frontend and backend here work on the default port to keep things simple for beginners. You have a valid point though. Trying to run the rails or node backend with this would definitely cause port conflicts. Using [cross-env](https://www.npmjs.com/package/cross-env) could be a good idea. Shipping with a default port and providing instructions to change the port in the readme would be a great addition.

**Comment by deksden** [comment]
I m totally for begginer's simplicity of starting playing with stuff. But as for now you can not run this project in default configuration from repo : you should change port. Changing port for CreateReactApp-based project is not transparent - you should do some googling.

1) For me, solution was as simple as adding .env file with "PORT=4100" line inside - React is already configured to use dotenv file. 

2) Or, maybe project should have one more dev package (cross-env) and we should change start script in package.json. 

But i m sure we should do something - 1) or 2)
