### ISSUE TITLE
#tag tab disappears when move to another tab

### ISSUE THREAD

**Issue by tony-shannon** [gothinkster/react-redux-realworld-example-app#54]
Just testing this UI frontend against the #qewd backend.
Works nicely..
However
if I select a #tag and a tab opens (see #qewd tag tab open in this example)
![image](https://cloud.githubusercontent.com/assets/939996/25657293/0ef76504-2ff5-11e7-849f-f36aebc22230.png)

.. then move to another tab, the #tag tab disappears..
![image](https://cloud.githubusercontent.com/assets/939996/25657253/df0ad682-2ff4-11e7-99d9-a5c5a400aa76.png)

Perhaps this is expected behaviour , but doesnt make sense from usability perspective.
The #tag tab should remain open until tab is closed

**Comment by EricSimons** [comment]
This is actually expected behavior 👍
