### ISSUE TITLE
TypeError: Cannot read property 'articles' of undefined

### ISSUE THREAD

**Issue by fortunto2** [gothinkster/react-redux-realworld-example-app#60]
Hello, the error is strange.

When you go to the user's profile everything is fine, but later if you switch to Favorites and back the user changes to undifined

Django backend

![2017-05-11 01-53-04](https://cloud.githubusercontent.com/assets/1236751/25920821/9d997796-35ec-11e7-938f-99dfa239dd6c.png)

**Comment by fortunto2** [comment]
same error
```
Uncaught (in promise) TypeError: Cannot read property 'tags' of undefined
```
`GET http://127.0.0.1:8000/api/articles/feed?limit=10&offset=0 404 (Not Found)`

**Comment by wiesson** [comment]
Despite various other errors - I updated `redux-logger` to `^3.0.1`, `react-redux` to `5.0.4` and wrapped the `getMiddleware()` with the redux `compose(...) function`

store.js:

```js
import { applyMiddleware, compose, createStore } from 'redux';
import { createLogger } from 'redux-logger'
import { promiseMiddleware, localStorageMiddleware } from './middleware';
import reducer from './reducer';

const getMiddleware = () => {
  if (process.env.NODE_ENV === 'production') {
    return applyMiddleware(promiseMiddleware, localStorageMiddleware);
  } else {
    // Enable additional logging in non-production environments.
    return applyMiddleware(promiseMiddleware, localStorageMiddleware, createLogger())
  }
}

const store = createStore(reducer, compose(getMiddleware(), window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()))

export default store;
```

Works!

**Comment by EricSimons** [comment]
@wiesson — wanna make a PR with your changes to this repo? :)

**Comment by wiesson** [comment]
@fortunto2, please pull and test again. Should be resolved!

**Comment by EricSimons** [comment]
Fixed with https://github.com/gothinkster/react-redux-realworld-example-app/commit/e6813ad86de965f65ed1cfbd7c244cb1c1270dd4
