### ISSUE TITLE
Fails silently on node 7.7.2

### ISSUE THREAD

**Issue by omidfi** [gothinkster/react-redux-realworld-example-app#61]
That version of node js makes react-create-app fail silently. Basically you will npm start, and you will get just a couple of warnings. 

If your node version is that, you need to update your react-scripts module to latest. 

Would be nice if the maintainers had time to update the package.json, I can send a PR too.

**Comment by SandeeshS** [comment]
@omidfi you can go ahead and create a PR for this, we'd gladly accept.

**Comment by EricSimons** [comment]
Thanks for the PR @omidfi!
