### ISSUE TITLE
Linting?

### ISSUE THREAD

**Issue by njj** [gothinkster/react-redux-realworld-example-app#7]
Do you think this project could benefit from having a unified style and linting implemented?

**Comment by vkarpov15** [comment]
I can see arguments either way. On one hand, linting is key for production repos, but on the other hand I want to minimize outside dependencies to keep things simple. What are your thoughts @njj?

**Comment by njj** [comment]
@vkarpov15 Yeah if you don't plan on having a lot of people contributing to this project, then I would say keeping it simple is best.
