### ISSUE TITLE
real-world example will not work with Node 4

### ISSUE THREAD

**Issue by wolendranh** [gothinkster/react-redux-realworld-example-app#82]
Hi!

the real-world example will not work with node 4. Because of related issue in [react-scripts ](https://github.com/facebookincubator/create-react-app/issues/2826)
Had to update to 6.0.0 on Mac machine.

Maybe it is obvious but I had to spend some time to get it. Is it possible to update readme for example?

I can volunteer for pull request if that's ok.

**Comment by wiesson** [comment]
The current version of node is v8.4.0 (?)
