### ISSUE TITLE
Can we use webpack

### ISSUE THREAD

**Issue by kamalendugarai** [gothinkster/react-redux-realworld-example-app#92]
There are many developer working with react redux paradigm, who streamline workflow with webpack. So, it would be nice if we can use webpack here.

**Comment by wiesson** [comment]
The example app is based on https://github.com/facebookincubator/create-react-app which obviously does use webpack.

You need to run `eject` to create your own config. https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup

**Comment by kamalendugarai** [comment]
Thanks for pointing me out to the link. This is awesome. Thanks for the help

**Comment by wiesson** [comment]
Then you may close the issue? :)
